server.port=8186
spring.application.name=pega

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=UNRESTRICTED

# Configurações de Autenticação Basic para o Pega Simulador
# Em produção/homologação, essas variáveis devem ser injetadas pelas variáveis de ambiente do Azure Key Vault
simulator.pega.auth.username=${PEGA_BASIC_AUTH_USERNAME:appview_local}
simulator.pega.auth.password=${PEGA_BASIC_AUTH_PASSWORD:dev_secret_123}

# Configuração do Rate Limiter para simular o gargalo de Pega (100 req/min)
resilience4j.ratelimiter.instances.pegaServer.limit-for-period=100
resilience4j.ratelimiter.instances.pegaServer.limit-refresh-period=1m
resilience4j.ratelimiter.instances.pegaServer.timeout-duration=0s
