server.port=${PORT:8085}
spring.application.name=prestador

prestador.sim.default-mode=${SIM_MODE:success}
prestador.sim.default-delay-ms=${DEFAULT_DELAY_MS:100}

app.security.basic.username=${PRESTADOR_USERNAME:appview}
app.security.basic.password=${PRESTADOR_PASSWORD:appview-secret-123}

management.endpoints.web.exposure.include=health,info,prometheus

